export enum ModalState {
  CHECK_LISTS_INFORMATION,
  CHECK_LISTS_ENTER_EMAIL,
  THANKS_FOR_BUY,
  FREE_DOCS_BAG_INFORMATION,
  FREE_DOCS_BAG_ENTER_EMAIL,
  DOCS_SENT,
  ERROR_WITH_DOCS_POST,
  CHECK_OBJ_INPUT_NUM,
  CHECK_OBJ_INPUT_EMAIL,
  CHECK_OWNER_INPUT_INFO,
  CHECK_OWNER_INPUT_EMAIL,
  INFORMATION_SENT,
  WANT_TO_LEND_FLAT,
  AGENT_FOR_CONTRACT,
  CONCIERGE_SERVICE,
  KEY_SEARCH,
  THANKS_FOR_ORDER,
}

export enum WindowSize {
  //min-width 1440 px
  XL,
  //max-width 1439 px and min-width 1024 px
  LG,
  MD,
}
